--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/platz1de/StatAPI
build-by-default: true
projects:
  StatAPI:
    icon: "icon.png"
    path: ""
    libs:
      - src: poggit/libasynql/libasynql
        version: ^3.4.0
        branch: 4.0
...
